name: The Pixel Heart Blog
description: 
avatar: https://avatars3.githubusercontent.com/u/3011454?v=2&s=200

footer-links:
  dribbble: 
  email: 
  facebook: pixelheartmusic
  flickr: 
  github:
  instagram: 
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: pixelheartmusic
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

disqus: 
google_analytics: 
url: http://thepixelheart.github.io/
baseurl: ""

markdown: kramdown
#redcarpet:
#  extensions: ["autolink", "tables"]

highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
